apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leafresh-be.fullname" . }}-secret
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}