apiVersion: v1
kind: Service
metadata:
  name: {{ include "leafresh-be.fullname" . }}
  labels:
    app: {{ include "leafresh-be.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "leafresh-be.name" . }}
