spring:
  application:
    name: backend

  profiles:
    active: ${spring_profiles_active}

  jackson:
    time-zone: Asia/Seoul

  security:
    basic:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  forward-headers-strategy: framework

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    ktb.leafresh.backend: DEBUG

jwt:
  secret: ${jwt_secret}

kakao:
  client-id: ${kakao_client_id}
  client-secret: ${kakao_client_secret}

cookie:
  secure: true

ai-server:
  text-base-url: ${text_ai_server_base_url}
  image-base-url: ${image_ai_server_base_url}

security:
  allowed-origins:
    - https://leafresh.app
    - https://localhost:3000
    - http://localhost:8080
    - https://dev-leafresh.app
    - https://be.dev-leafresh.app
    - https://local.dev-leafresh.app:3000
    - https://be.dev-leafresh.app
    - https://springboot.dev-leafresh.app
