spring:
  datasource:
    url: jdbc:mysql://${prod_db_host}:${db_port}/${prod_db_name}
    username: ${prod_db_user}
    password: ${prod_db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${prod_cache_host}
      port: ${prod_cache_port}

cookie:
  secure: true
