spring:
  datasource:
    url: jdbc:mysql://${DOCKER_PROD_DB_HOST}:${DB_PORT}/${DOCKER_PROD_DB_NAME}
    username: ${DOCKER_PROD_DB_USER}
    password: ${DOCKER_PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${DOCKER_PROD_CACHE_HOST}
      port: ${DOCKER_PROD_CACHE_PORT}

redis:
  redisson:
    address: redis://${SPRING_DATA_REDIS_HOST}:${SPRING_DATA_REDIS_PORT}
  bloom:
    host: ${DOCKER_PROD_CACHE_HOST}
    port: ${DOCKER_PROD_CACHE_PORT}

cookie:
  secure: true
  samesite: ${DOCKER_PROD_COOKIE_SAMESITE:None}
  domain: ${DOCKER_PROD_COOKIE_DOMAIN:.leafresh.app}

gcp:
  project-id: ${GCP_PROJECT_ID}
  credentials:
    location: classpath:${GCP_CREDENTIALS_LOCATION}
  storage:
    bucket: ${GCP_STORAGE_BUCKET}
    lock-image-url: https://storage.googleapis.com/${GCP_STORAGE_BUCKET}/init/badge/common/%E1%84%8C%E1%85%A1%E1%84%86%E1%85%AE%E1%86%AF%E1%84%89%E1%85%AC.png
  pubsub:
    topics:
      order: ${GCP_PUBSUB_TOPIC_ORDER}
      image-verification: ${GCP_PUBSUB_TOPIC_IMAGE_VERIFICATION}
    subscriptions:
      order: ${GCP_PUBSUB_SUBSCRIPTION_ORDER}
      dlq: ${GCP_PUBSUB_SUBSCRIPTION_ORDER_DLQ}
      image-verification-result: ${GCP_PUBSUB_SUBSCRIPTION_IMAGE_VERIFICATION_RESULT}
      verification-dlq: ${GCP_PUBSUB_SUBSCRIPTION_IMAGE_VERIFICATION_RESULT_DLQ}
