spring:
  application:
    name: backend

  security:
    basic:
      enabled: false

  datasource:
    url: jdbc:mysql://${local_db_host}:${db_port}/${local_db_name}
    username: ${local_db_user}
    password: ${local_db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  data:
    redis:
      host: ${local_cache_host}
      port: ${local_cache_port}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret: ${jwt_secret}

kakao:
  client-id: ${kakao_client_id}
  redirect-uri: ${kakao_redirect_uri}
  client-secret: ${kakao_client_secret}
