spring:
  datasource:
    url: jdbc:mysql://${LOCAL_DB_HOST}:${DB_PORT}/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${LOCAL_CACHE_HOST}
      port: ${LOCAL_CACHE_PORT}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

redis:
  redisson:
    address: redis://${SPRING_DATA_REDIS_HOST}:${SPRING_DATA_REDIS_PORT}
  bloom:
    host: ${LOCAL_CACHE_HOST}
    port: ${LOCAL_CACHE_PORT}

cookie:
  secure: false
  samesite: ${LOCAL_COOKIE_SAMESITE:Strict}
  domain: ${LOCAL_COOKIE_DOMAIN:localhost}

gcp:
  project-id: ${GCP_PROJECT_ID}
  credentials:
    location: classpath:${GCP_CREDENTIALS_LOCATION}
  storage:
    bucket: ${GCP_STORAGE_BUCKET}
  pubsub:
    topics:
      order: ${GCP_PUBSUB_TOPIC_ORDER}
      image-verification: ${GCP_PUBSUB_TOPIC_IMAGE_VERIFICATION}
    subscriptions:
      order: ${GCP_PUBSUB_SUBSCRIPTION_ORDER}
      dlq: ${GCP_PUBSUB_SUBSCRIPTION_ORDER_DLQ}

logging:
  level:
    com.p6spy: DEBUG
    org.hibernate.stat: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
