# Swagger 문서 생성용 프로필 설정
spring:
  # H2 인메모리 데이터베이스 사용
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false

  # Redis 비활성화
  data:
    redis:
      repositories:
        enabled: false
        
  # 자동 구성 제외
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.cloud.gcp.autoconfigure.pubsub.GcpPubSubAutoConfiguration
      - org.redisson.spring.starter.RedissonAutoConfiguration

# Swagger UI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    
# 애플리케이션 설정
server:
  port: 8080
  servlet:
    context-path: /

# JWT 설정 (더미 값)
jwt:
  secret: dGVzdC1zZWNyZXQta2V5LWZvci1zd2FnZ2VyLWRvY3VtZW50YXRpb24tZ2VuZXJhdGlvbg==
  access-token:
    expiration: 86400000
  refresh-token:
    expiration: 1209600000

# OAuth 설정 (더미 값)
kakao:
  client-id: dummy-client-id
  client-secret: dummy-client-secret

# 쿠키 설정 (더미 값)
cookie:
  domain: localhost
  secure: false
  same-site: Strict

# 이미지 URL (더미 값)  
lock-image-url: "https://leafresh-images.s3.ap-northeast-2.amazonaws.com/init/badge/common/%E1%84%8C%E1%85%A1%E1%84%86%E1%85%AE%E1%86%AF%E1%84%89%E1%85%AC.png"

# AWS 설정 비활성화
cloud:
  aws:
    credentials:
      access-key: dummy
      secret-key: dummy
    region:
      static: ap-northeast-2
    s3:
      bucket: dummy-bucket
      
# GCP Pub/Sub 비활성화
gcp:
  project-id: dummy-project
  pubsub:
    enabled: false

# Redis 설정 (더미 값)
redis:
  enabled: false
  host: localhost
  port: 6379

# AI 서비스 URL (더미 값)
ai:
  chatbot:
    base-url: "http://localhost:8081"
  verification:
    base-url: "http://localhost:8082" 
  feedback:
    base-url: "http://localhost:8083"

# Scheduler 비활성화
scheduling:
  enabled: false

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    ktb.leafresh.backend: INFO
    org.redisson: OFF
    redis.clients.jedis: OFF
    org.springframework.cloud.gcp: OFF
    com.google.cloud: OFF
    com.amazonaws: OFF
    
# Management endpoints 설정 (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
