spring:
  datasource:
    url: jdbc:mysql://${eks_prod_db_host}:${db_port}/${eks_prod_db_name}
    username: ${eks_prod_db_user}
    password: ${eks_prod_db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${eks_prod_cache_host}
      port: ${eks_prod_cache_port}

cookie:
  secure: true
  samesite: ${eks_prod_cookie_domain:none}
  domain: ${eks_prod_cookie_samesite:.leafresh.app}

gcp:
  project-id: ${gcp_project_id}
  credentials:
    location: classpath:${gcp_credentials_location}
  storage:
    bucket: ${gcp_storage_bucket}
