spring:
  datasource:
    url: jdbc:mysql://${BIGBANG_PROD_DB_HOST}:${DB_PORT}/${BIGBANG_PROD_DB_NAME}
    username: ${BIGBANG_PROD_DB_USER}
    password: ${BIGBANG_PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${BIGBANG_PROD_CACHE_HOST}
      port: ${BIGBANG_PROD_CACHE_PORT}

cookie:
  secure: true
  samesite: ${BIGBANG_PROD_COOKIE_SAMESITE:none}

gcp:
  project-id: ${GCP_PROJECT_ID}
  credentials:
    location: classpath:${GCP_CREDENTIALS_LOCATION}
  storage:
    bucket: ${GCP_STORAGE_BUCKET}
