# Swagger 문서 생성용 프로필 설정
spring:
  # H2 인메모리 데이터베이스 사용
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        
  # 메시지 큐 비활성화
  cloud:
    gcp:
      pubsub:
        enabled: false

  # Task Execution & Scheduling 비활성화
  task:
    execution:
      pool:
        core-size: 1
        max-size: 1
    scheduling:
      pool:
        size: 1

# Swagger UI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    
# 애플리케이션 설정
server:
  port: 8080
  servlet:
    context-path: /

# JWT 설정 (더미 값)
jwt:
  secret: dGVzdC1zZWNyZXQta2V5LWZvci1zd2FnZ2VyLWRvY3VtZW50YXRpb24tZ2VuZXJhdGlvbg==
  access-token:
    expiration: 86400000
  refresh-token:
    expiration: 1209600000

# OAuth 설정 (더미 값)
kakao:
  client-id: dummy-client-id
  client-secret: dummy-client-secret

# 쿠키 설정 (더미 값)
cookie:
  domain: localhost
  secure: false
  same-site: Strict

# 이미지 URL (더미 값)  
lock-image-url: "https://leafresh-images.s3.ap-northeast-2.amazonaws.com/init/badge/common/%E1%84%8C%E1%85%A1%E1%84%86%E1%85%AE%E1%86%AF%E1%84%89%E1%85%AC.png"

# AWS 설정 비활성화
cloud:
  aws:
    credentials:
      access-key: dummy
      secret-key: dummy
    region:
      static: ap-northeast-2
    s3:
      bucket: dummy-bucket
      
# GCP Pub/Sub 비활성화
gcp:
  project-id: dummy-project
  pubsub:
    enabled: false
    feedback:
      topic: dummy-feedback-topic
      subscription: dummy-feedback-subscription
      dlq-subscription: dummy-feedback-dlq-subscription
    verification:
      topic: dummy-verification-topic
      subscription: dummy-verification-subscription
      dlq-subscription: dummy-verification-dlq-subscription

# Redis 설정 (더미 값)
redis:
  enabled: false
  redisson:
    address: "redis://localhost:6379"
  host: localhost
  port: 6379

# AI 서비스 URL (더미 값)
ai:
  chatbot:
    base-url: "http://localhost:8081"
  verification:
    base-url: "http://localhost:8082" 
  feedback:
    base-url: "http://localhost:8083"

# Scheduler 비활성화
scheduling:
  enabled: false

# ShedLock 비활성화
shedlock:
  defaults:
    lock-at-most-for: PT30M
    lock-at-least-for: PT5M

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.cloud.gcp: WARN
    com.google.cloud: WARN
    ktb.leafresh.backend: INFO
    org.redisson: WARN
    redis.clients.jedis: WARN
    
# Management endpoints 설정 (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      
# 외부 의존성 Mock 활성화 플래그
mock:
  enabled: true
  redis: true
  aws: true
  gcp: true
  external-apis: true
