spring:
  application:
    name: backend

  profiles:
    active: local

  security:
    basic:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG

jwt:
  secret: ${jwt_secret}

kakao:
  client-id: ${kakao_client_id}
  redirect-uri: ${kakao_redirect_uri}
  client-secret: ${kakao_client_secret}

cookie:
  secure: true

ai-server:
  base-url: ${ai_server_base_url}
