name: Backend CI/CD
 
on:
  push:
    tags:
      - 'v*-dev'
      - 'v*'
  pull_request:
    branches: ["develop", "main"]

env:
  REGION: asia-northeast3
  BLUE_MIG_NAME: leafresh-fe-blue-template
  GREEN_MIG_NAME: leafresh-fe-green-template
  LOAD_BALANCER_NAME: leafresh-https-lb
  URL_MAP_NAME: leafresh-https-lb  # URL Map 이름
  BLUE_BACKEND_SERVICE_NAME: leafresh-fe-blue-bs
  GREEN_BACKEND_SERVICE_NAME: leafresh-fe-green-bs

    
jobs:
  sync-env-to-GSM:
    name: Upload .env to Secret Manager
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV_JSON }}

      - name: Set GCP Secret Name based on branch
        id: set-env-vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID_PROD }}" >> $GITHUB_ENV
            echo "SECRET_NAME=env-be-prod" >> $GITHUB_ENV
            echo "${{ secrets.ENV_BE_PROD }}" > .env
            echo "Using A project and production .env"
          else
            echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID_DEV }}" >> $GITHUB_ENV
            echo "SECRET_NAME=env-be-dev" >> $GITHUB_ENV
            echo "${{ secrets.ENV_BE_DEV }}" > .env
            echo "Using B project and development .env"
          fi

      - name: Setup Google Cloud SDK and Set GCP Project
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Change to Correct Project
        run: |
          echo '${{ secrets.GCP_SA_KEY_DEV_BASE64 }}' | base64 -d > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project $GCP_PROJECT_ID

      - name: Confirm active gcloud project
        run: gcloud config get-value project

      - name: Validate .env content
        run: |
          if [[ ! -s .env ]]; then
            echo ".env file EMPTY."
            exit 1
          fi

      - name: Push .env to Secret Manager
        run: |
          if gcloud secrets describe "$SECRET_NAME" >/dev/null 2>&1; then
            echo "Secret $SECRET_NAME exists, adding new version..."
            gcloud secrets versions add "$SECRET_NAME" --data-file=.env
          else
            echo "Secret $SECRET_NAME does not exist, creating..."
            gcloud secrets create "$SECRET_NAME" --data-file=.env --replication-policy=automatic
          fi

  unit-test:                                    # 단위 테스트를 수행하는 Job (develop 브랜치 PR 대상)
    name: Unit Test
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3              # 소스코드 체크아웃

      - name: Set up JDK 21                    # Java 21 환경 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Grant Gradle permission          # gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Cache Gradle dependencies        # Gradle 캐시로 빌드 속도 향상
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts', 'build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Tests                        # 단위 테스트 실행
        run: ./gradlew test
        
  integration-test:
    name: Integration Test
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Rlatldms!2!3
          MYSQL_DATABASE: leafresh
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --protocol=tcp"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Create .env file from GitHub Secret
        run: echo "${{ secrets.ENV_BE_DEV }}" > .env
      
      - name: Create GCP credentials file
        run: echo "${{ secrets.GCP_SA_KEY_DEV_BASE64 }}" | base64 -d > /home/runner/leafresh2-428172295b3d.json

      - name: Build Spring Boot App
        run: ./gradlew bootJar

      - name: Start Spring Boot App with env
        run: |
          source .env
          nohup sh -c '. env && java -jar build/libs/*.jar' > app.log 2>&1 &
          echo "✅ Java started, waiting for Spring Boot..."
          sleep 150
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "✅ Spring Boot is UP"
              break
            fi
            echo "⏳ Waiting for Spring Boot..."
            sleep 2
          done
      - name: Integration Test
        run: |
          curl -v http://localhost:8080/api/challenges/group/categories || (
            echo "API call failed"
            echo "===== APP.LOG START ====="
            cat app.log || echo "app.log not found"
            echo "===== APP.LOG END ====="
            exit 1
          )
      - name: Stop Spring Boot App
        run: pkill -f 'java -jar'

  build-dev:                                    # develop 브랜치에서 Docker 이미지 빌드 및 푸시
    name: Build and Push Docker (dev)
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3              # 소스코드 체크아웃

      - name: Set up Docker Buildx             # Docker Buildx 설정
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Docker Hub              # Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image      # Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jchanho99/backend-develop:latest
          cache-from: type=gha,scope=build-backend-develop
          cache-to: type=gha,mode=max,scope=build-backend-develop

  build-prod:                                   # main 브랜치에서 Docker 이미지 빌드 및 푸시
    name: Build and Push Docker (prod)
    needs: [integration-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3              # 코드 체크아웃

      - name: Set up Docker Buildx             # Docker Buildx 설정
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Docker Hub              # Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image to Docker Hub     # Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jchanho99/backend-prod:latest
          cache-from: type=gha,scope=build-backend-prod
          cache-to: type=gha,mode=max,scope=build-backend-prod


  deploy-dev:
    name: BE Docker 배포 (Develop)
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-dev') && github.base_ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set-status.outputs.status }}
    steps:
      - uses: actions/checkout@v3              # 소스코드 체크아웃

      - name: Extract tag name
        id: tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Deploy Backend (Develop) via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: SHORT_SHA
          script: |
            set -e
            echo "GCP 인증 및 Docker 로그인"
            echo '${{ secrets.GCP_SA_KEY_GCS_BASE64 }}' | base64 -d > ~/leafresh-gcs.json
            sudo mv ~/leafresh-gcs.json /home/ubuntu/backend/app/leafresh-gcs.json
            sudo chown ubuntu:ubuntu /home/ubuntu/backend/app/leafresh-gcs.json
            sudo chmod 600 /home/ubuntu/backend/app/leafresh-gcs.json

            echo "Secret Manager에서 .env 기져오기"
            # .env를 홈 디렉토리에 우선 저장
            if ! gcloud secrets versions access latest \
              --secret="env-be-dev" \
              --project="${{ secrets.GCP_PROJECT_ID_DEV }}" > ~/env-be-dev.tmp; then
              echo ".env 파일 다운로드 실패"
              exit 1
            fi
            
            # 권한 수정 후 앱 디렉토리로 이동
            sudo mv ~/env-be-dev.tmp /home/ubuntu/backend/app/.env
            sudo chown ubuntu:ubuntu /home/ubuntu/backend/app/.env
            sudo chmod 600 /home/ubuntu/backend/app/.env
            
            echo "[DEV] 환경 배포 중"
            cd /home/ubuntu/backend
            sudo docker compose down --rmi all
            sudo docker compose pull
            sudo docker compose up -d
            sudo docker compose ps

      - name: Upload tag-versioned image to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag and Push Docker Image (tag = ${{ env.TAG_NAME }})
        run: |
          docker pull jchanho99/backend-develop:latest
          docker image tag jchanho99/backend-develop:latest temp-image-with-label

          # 임시 컨테이너 생성 후 레이블 추가로 digest 변경
          docker container create --name temp-container temp-image-with-label
          docker commit --change "LABEL force-push-tag=${TAG_NAME}-$(date +%s)" temp-container jchanho99/backend-develop:${TAG_NAME}

          # 정리
          docker container stop temp-container
          docker container rm temp-container
          docker image rm temp-image-with-label
          docker push jchanho99/backend-develop:${TAG_NAME}
      
      - name: Set Status (Dev)
        id: set-status
        if: success()
        run: echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Set Status (Dev Failure)
        if: failure() && steps.deploy-dev.outcome == 'failure' # deploy-step이 실패했을 때만
        run: echo "status=failure" >> "$GITHUB_OUTPUT"

  deploy-prod:
    name: BE Docker 배포 (Prod)
    if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-dev') && github.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set-status.outputs.status }}
    steps:
      - name: Extract tag name
        id: tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/v}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV0

      - name: Determine current active MIG (Blue or Green)
        id: get_active_mig
        run: |
          # Load Balancer의 URL Map에서 현재 트래픽이 어느 백엔드로 향하고 있는지 확인합니다.
          # Artifact Registry 버전과 동일한 로직을 사용합니다.
          
          ACTIVE_MIG_NAME=""
          INACTIVE_MIG_NAME=""
          ACTIVE_BACKEND_SERVICE=""
          INACTIVE_BACKEND_SERVICE=""

          CURRENT_DEFAULT_SERVICE=$(gcloud compute url-maps describe ${{ env.URL_MAP_NAME }} --project ${{ env.PROJECT_ID_PROD }} --format="value(defaultService)" | awk -F'/' '{print $NF}')

          if [[ "$CURRENT_DEFAULT_SERVICE" == "${{ env.BLUE_BACKEND_SERVICE_NAME }}" ]]; then
            echo "Current active backend is BLUE. Deploying to GREEN."
            ACTIVE_MIG_NAME="${{ env.BLUE_MIG_NAME }}"
            INACTIVE_MIG_NAME="${{ env.GREEN_MIG_NAME }}"
            ACTIVE_BACKEND_SERVICE="${{ env.BLUE_BACKEND_SERVICE_NAME }}"
            INACTIVE_BACKEND_SERVICE="${{ env.GREEN_BACKEND_SERVICE_NAME }}"
          else
            echo "Current active backend is GREEN. Deploying to BLUE."
            ACTIVE_MIG_NAME="${{ env.GREEN_MIG_NAME }}"
            INACTIVE_MIG_NAME="${{ env.BLUE_MIG_NAME }}"
            ACTIVE_BACKEND_SERVICE="${{ env.GREEN_BACKEND_SERVICE_NAME }}"
            INACTIVE_BACKEND_SERVICE="${{ env.BLUE_BACKEND_SERVICE_NAME }}"
          fi
          echo "active_mig_name=$ACTIVE_MIG_NAME" >> $GITHUB_OUTPUT
          echo "inactive_mig_name=$INACTIVE_MIG_NAME" >> $GITHUB_OUTPUT
          echo "active_backend_service=$ACTIVE_BACKEND_SERVICE" >> $GITHUB_OUTPUT
          echo "inactive_backend_service=$INACTIVE_BACKEND_SERVICE" >> $GITHUB_OUTPUT

      - name: Get current MIG instance template name
        id: get_template
        run: |
          TEMPLATE_NAME=$(gcloud compute instance-groups managed describe ${{ steps.get_active_mig.outputs.inactive_mig_name }} --zone ${{ env.REGION }}-a --project ${{ env.PROJECT_ID }} --format="value(instanceTemplate)" | awk -F'/' '{print $NF}')
          echo "current_template_name=$TEMPLATE_NAME" >> $GITHUB_OUTPUT
          
      - name: Create new instance template for inactive MIG
        id: create_new_template
        run: |
          NEW_TEMPLATE_NAME="${{ steps.get_active_mig.outputs.inactive_mig_name }}-${{ github.sha }}"
          FULL_IMAGE_NAME="jchanho99/backend-prod"

          gcloud compute instance-templates create $NEW_TEMPLATE_NAME \
            --project ${{ secrets.GCP_PROJECT_ID_PROD }} \
            --machine-type e2-custom-2-3072 \
            --image-family ubuntu-2204-lts \
            --image-project ubuntu-os-cloud \
            --boot-disk-size 20GB \
            --metadata startup-script="""#! /bin/bash
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg lsb-release
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            sudo systemctl start docker
            sudo systemctl enable docker

            # .env를 홈 디렉토리에 우선 저장
            if ! gcloud secrets versions access latest \
              --secret="env-be-prod" \
              --project="${{ secrets.GCP_PROJECT_ID_PROD }}" > ~/.env; then
              echo ".env 파일 다운로드 실패"
              exit 1
            fi
            
            sudo docker pull $FULL_IMAGE_NAME:latest
            sudo docker run -d -p 80:80 --env-file ~/.env $FULL_IMAGE_NAME:latest
            """ \
            --tags http-server,https-server \
            --scopes cloud-platform # 필요한 스코프 추가

          echo "new_template_name=$NEW_TEMPLATE_NAME" >> $GITHUB_OUTPUT

      - name: Update inactive MIG with new instance template
        run: |
          gcloud compute instance-groups managed set-instance-template ${{ steps.get_active_mig.outputs.inactive_mig_name }} \
            --template ${{ steps.create_new_template.outputs.new_template_name }} \
            --zone ${{ env.REGION }}-a \
            --project ${{ secrets.GCP_PROJECT_ID_PROD }}
          
          echo "Waiting for rolling update of ${{ steps.get_active_mig.outputs.inactive_mig_name }} to complete..."
          gcloud compute instance-groups managed wait-until --stable ${{ steps.get_active_mig.outputs.inactive_mig_name }} --zone ${{ env.REGION }}-a --project ${{ secrets.GCP_PROJECT_ID_PROD }}
          
      - name: Health Check for inactive MIG
        run: |
          echo "Performing health check on newly deployed MIG (${{ steps.get_active_mig.outputs.inactive_mig_name }})..."
          echo "Simulating health check success. (Replace with actual health check logic)"

      - name: Switch Load Balancer traffic to new MIG
        run: |
          echo "Switching Load Balancer traffic from ${{ steps.get_active_mig.outputs.active_backend_service }} to ${{ steps.get_active_mig.outputs.inactive_backend_service }}..."
          
          gcloud compute url-maps set-default-service ${{ env.URL_MAP_NAME }} \
            --default-service ${{ steps.get_active_mig.outputs.inactive_backend_service }} \
            --project ${{ secrets.GCP_PROJECT_ID_PROD }} \
            --global

          echo "Traffic switch initiated. It may take some time for changes to propagate."
          
      - name: Clean up old instance template (optional)
        run: |
          OLD_TEMPLATE_NAME="${{ steps.get_template.outputs.current_template_name }}"
          if [[ -n "$OLD_TEMPLATE_NAME" ]]; then
            echo "Deleting old instance template: $OLD_TEMPLATE_NAME"
            gcloud compute instance-templates delete $OLD_TEMPLATE_NAME --project ${{ secrets.GCP_PROJECT_ID_PROD }} --quiet
          fi

      - name: Tag and Push Docker Image (tag = ${{ env.TAG_NAME }})
        run: |
          docker pull jchanho99/backend-prod:latest
          docker image tag jchanho99/backend-prod:latest temp-image-with-label

          # 임시 컨테이너 생성 후 레이블 추가로 digest 변경
          docker container create --name temp-container temp-image-with-label
          docker commit --change "LABEL force-push-tag=${TAG_NAME}-$(date +%s)" temp-container jchanho99/backend-prod:${TAG_NAME}

          # 정리
          docker container stop temp-container
          docker container rm temp-container
          docker image rm temp-image-with-label

          # 푸시
          docker push jchanho99/backend-prod:${TAG_NAME}

      - name: Set Status (Prod)
        id: set-status
        if: success()
        run: echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Set Status (Prod Failure)
        if: failure() && steps.deploy-prod.outcome == 'failure' # deploy-step이 실패했을 때만
        run: echo "status=failure" >> "$GITHUB_OUTPUT"

  notify:
    name: Discord Notification
    needs: [deploy-dev, deploy-prod]
    if: |
      always() &&
      (
        needs.deploy-dev.result != 'skipped' ||
        needs.deploy-prod.result != 'skipped'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ "${{ needs.deploy-dev.result }}" != 'skipped' ]]; then
            STATUS="${{ needs.deploy-dev.outputs.status }}"
          elif [[ "${{ needs.deploy-prod.result }}" != 'skipped' ]]; then
            STATUS="${{ needs.deploy-prod.outputs.status }}"
          else
            STATUS="unknown"
          fi

          if [[ "$STATUS" == "success" ]]; then
            MESSAGE="✅ [${TAG}] 배포 완료"
          elif [[ "$STATUS" == "failure" ]]; then
            MESSAGE="🚨 [${TAG}] 배포 실패. actions에서 로그를 확인하세요."
          else
            MESSAGE="⚠️ [${TAG}] 배포 상태를 알 수 없습니다."
          fi

          echo "message=$MESSAGE" >> $GITHUB_OUTPUT

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
